// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSKqblv4kyPW9Dww6kXdpJOBLTfneRxM4',
    appId: '1:414011992436:web:81800c9ffcfc5a7ee2e421',
    messagingSenderId: '414011992436',
    projectId: 'tinderatrack-acf1a',
    authDomain: 'tinderatrack-acf1a.firebaseapp.com',
    storageBucket: 'tinderatrack-acf1a.firebasestorage.app',
    measurementId: 'G-5DLPKJD2PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqN755ujP9YuQxtU7_udQcLvW3riM2jeI',
    appId: '1:414011992436:android:1bce0c22bf982744e2e421',
    messagingSenderId: '414011992436',
    projectId: 'tinderatrack-acf1a',
    storageBucket: 'tinderatrack-acf1a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4UAsr5bX36Vg_2pgkcifsUcGxZHPaVCQ',
    appId: '1:414011992436:ios:15572a925482572be2e421',
    messagingSenderId: '414011992436',
    projectId: 'tinderatrack-acf1a',
    storageBucket: 'tinderatrack-acf1a.firebasestorage.app',
    iosClientId: '414011992436-cf87diusenqhsh5jgu6d39i7qaj8huk8.apps.googleusercontent.com',
    iosBundleId: 'com.tinderatrack.',
  );
}
